# Conexi贸n con la base de datos principal
database: 
  host: localhost
  user: root
  pass: 
  name: emergente
  port: 1521
  protocol: TCP
  motor: mysql
  
# Configuraci贸n de servidor SMTP
phpmailer:
  host: p3plcpnl0173.prod.phx3.secureserver.net
  user: dev@ocrend.com
  pass: Devocrend++
  port: 465

# Configuraci贸n de sesiones
sessions:
  life_time: 3600 

# Variables del framework
framework:
  debug: false
  version: 2.0.0

# Configuraci贸n del sitio
site:
  name: Emergente-Admin
  author: DevSystemVzla
  author_email: prinick@ocrend.com
  url: http://localhost/emergente/emergente-admin/
  timezone: America/Caracas
  frontend: http://localhost/emergente/
  router:
    path: localhost/emergente/emergente-admin/
    protocol: http
